# Generated by Django 3.2.2 on 2021-05-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_main', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='TITLE', max_length=200)),
                ('descriptions', models.TextField(db_column='CONTENTS', max_length=1000)),
                ('playlist', models.IntegerField(db_column='PLAYLIST')),
                ('whether_to_disclose', models.BooleanField(db_column='WHETHER_TO_DISCLOSE')),
                ('viewer_age', models.BooleanField(db_column='VIEWER_AGE')),
                ('age_limit', models.BooleanField(db_column='AGE_LIMIT')),
            ],
            options={
                'db_table': 'video_edit',
                'managed': False,
            },
        ),
    ]
