# Generated by Django 3.2.2 on 2021-05-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_main', '0003_videoedit'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMain',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='TITLE', max_length=200)),
                ('author_name', models.CharField(db_column='AUTHOR_NAME', max_length=30)),
                ('view_number', models.IntegerField(db_column='VIEW_NUMBER')),
                ('uploaded_at', models.DateField(auto_now_add=True, db_column='UPLOADED_AT')),
                ('descriptions', models.TextField(db_column='DESCRIPTIONS', max_length=1000)),
                ('playlist', models.IntegerField(db_column='PLAYLIST')),
                ('whether_to_disclose', models.BooleanField(db_column='WHETHER_TO_DISCLOSE')),
                ('viewer_age', models.BooleanField(db_column='VIEWER_AGE')),
                ('age_limit', models.BooleanField(db_column='AGE_LIMIT')),
            ],
            options={
                'db_table': 'video_upload',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='VideoEdit',
        ),
        migrations.DeleteModel(
            name='VideoList',
        ),
    ]
